-- =============================================================================
-- NOTE ON PROVENANCE (read before applying)
--
-- The "CreateSchema" / "CreateEnum" / "CreateTable" / "CreateIndex" /
-- "AddForeignKey" sections below were generated by
--   prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- (Prisma's schema engine computing empty→schema DDL directly, which does
-- not require a live database connection) and are byte-for-byte what
-- Prisma itself would write. They were NOT applied against a real
-- Postgres in this session — no Docker/Postgres instance was reachable —
-- so run `pnpm --filter api run prisma:migrate` (or `migrate deploy`)
-- against a real database and confirm it applies cleanly before trusting
-- this in production.
--
-- The "Row-level tenant isolation" section at the bottom is hand-written —
-- Prisma has no RLS support, so `migrate diff` cannot generate it. It
-- stays hand-written on every future migration that adds an
-- organizationId-bearing table. See
-- docs/architecture/security.md#row-level-security.
-- =============================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "StaffRole" AS ENUM ('ADMINISTRATOR', 'RECEPTION', 'NURSE', 'JUNIOR_DOCTOR', 'SENIOR_DOCTOR', 'SURGERY_COORDINATOR', 'PHARMACY', 'BILLING', 'INSURANCE', 'MARKETING');

-- CreateTable
CREATE TABLE "organizations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clinics" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "clinics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clinicId" TEXT,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "role" "StaffRole" NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "patients" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "clinicId" TEXT,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "dateOfBirth" TIMESTAMP(3) NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "passwordHash" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "patients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "actorType" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "organizations_deletedAt_idx" ON "organizations"("deletedAt");

-- CreateIndex
CREATE INDEX "clinics_organizationId_deletedAt_idx" ON "clinics"("organizationId", "deletedAt");

-- CreateIndex
CREATE INDEX "users_organizationId_deletedAt_idx" ON "users"("organizationId", "deletedAt");

-- CreateIndex
CREATE INDEX "users_clinicId_idx" ON "users"("clinicId");

-- CreateIndex
CREATE UNIQUE INDEX "users_organizationId_email_key" ON "users"("organizationId", "email");

-- CreateIndex
CREATE INDEX "patients_organizationId_deletedAt_idx" ON "patients"("organizationId", "deletedAt");

-- CreateIndex
CREATE INDEX "patients_clinicId_idx" ON "patients"("clinicId");

-- CreateIndex
CREATE INDEX "patients_phone_idx" ON "patients"("phone");

-- CreateIndex
CREATE INDEX "audit_logs_entityType_entityId_idx" ON "audit_logs"("entityType", "entityId");

-- AddForeignKey
ALTER TABLE "clinics" ADD CONSTRAINT "clinics_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patients" ADD CONSTRAINT "patients_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patients" ADD CONSTRAINT "patients_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- =============================================================================
-- Row-level tenant isolation (hand-written — see provenance note above)
--
-- Every table that carries organizationId gets an RLS policy comparing it
-- against a Postgres session variable, `app.current_organization_id`, that
-- the application sets at the start of each request/transaction — see
-- apps/api/src/prisma/tenant-context.service.ts.
--
-- FORCE ROW LEVEL SECURITY is used, not just ENABLE, because ENABLE alone
-- is bypassed by the table owner role — and the role the app's migrations
-- run as is typically the table owner. Without FORCE, this policy would
-- silently do nothing for the app's own connections.
--
-- Fails closed: current_setting(..., true) returns NULL if the session
-- variable was never set, and `"organizationId" = NULL` is never true in
-- SQL, so an application bug that forgets to set tenant context hides ALL
-- rows for that connection rather than leaking rows across tenants.
--
-- Organization itself is not RLS-scoped — it IS the tenant, there's no
-- parent tenant to scope it by. AuditLog is not yet RLS-scoped because it
-- does not carry organizationId in the current schema — flagged, not
-- solved here (see docs/architecture/open-questions.md).
-- =============================================================================

ALTER TABLE "clinics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "clinics" FORCE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
ALTER TABLE "patients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "patients" FORCE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "clinics"
  USING ("organizationId" = current_setting('app.current_organization_id', true));

CREATE POLICY "tenant_isolation" ON "users"
  USING ("organizationId" = current_setting('app.current_organization_id', true));

CREATE POLICY "tenant_isolation" ON "patients"
  USING ("organizationId" = current_setting('app.current_organization_id', true));
