export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  CARD = 'CARD',
  CREDIT = 'CREDIT',
  INSURANCE = 'INSURANCE',
  SPLIT = 'SPLIT',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  VOID = 'VOID',
}

export enum InsuranceClaimStatus {
  ELIGIBILITY_CHECK = 'ELIGIBILITY_CHECK',
  PRE_AUTH_REQUESTED = 'PRE_AUTH_REQUESTED',
  PRE_AUTH_APPROVED = 'PRE_AUTH_APPROVED',
  PRE_AUTH_DENIED = 'PRE_AUTH_DENIED',
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_PARTIALLY_APPROVED = 'CLAIM_PARTIALLY_APPROVED',
  CLAIM_REJECTED = 'CLAIM_REJECTED',
  SETTLED = 'SETTLED',
}
