export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  NURTURING = 'NURTURING',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
}

export enum LeadSource {
  WEBSITE = 'WEBSITE',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  CAMPAIGN = 'CAMPAIGN',
  REFERRAL = 'REFERRAL',
  CAMP = 'CAMP',
  WALK_IN = 'WALK_IN',
}

export enum AppointmentEntrySource {
  ONLINE_BOOKING = 'ONLINE_BOOKING',
  RECEPTION_WALK_IN = 'RECEPTION_WALK_IN',
  VIDEO_CONSULTATION = 'VIDEO_CONSULTATION',
  CAMP = 'CAMP',
}

export enum AppointmentStatus {
  REQUESTED = 'REQUESTED',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum EncounterStatus {
  OPEN = 'OPEN',
  IN_CONSULTATION = 'IN_CONSULTATION',
  CLOSED = 'CLOSED',
}
